apiVersion: apps/v1
kind: Deployment
metadata:
   name: postgresdb-deployment
   labels:
       app: postgresdb
spec:
   replicas: 1
   selector:
      matchLabels:
         app: postgresdb
   template:
      metadata:
         labels:
            app: postgresdb
      spec:
         containers:
         - name: postgresdb
           image: postgres:14-alpine
           ports:
           - containerPort: 5432
           env:
           - name: POSTGRES_USER
             valueFrom:
               secretKeyRef:
                 name: postgresdb-secret
                 key: postgres-root-username
           - name: POSTGRES_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: postgresdb-secret
                 key: postgres-root-password
           - name: POSTGRES_DB
             value: customerdb
---
apiVersion: v1
kind: Service
metadata:
   name: postgresdb-service
spec:
   selector:
      app: postgresdb
   ports:
      - protocol: TCP
        port: 5432
        targetPort: 5432
